<?php 
/////////////////////////////////////////////////////////////////////////////////////////
//
//	this file has been generated by sformi, the clever tool for lazy developers.
//
//	template v5 - 08082007
//
//	160710 - v1
//

ini_set ('error_reporting', E_ALL);
ini_set ('display_errors', '1');

session_start();

require_once('./_config.php');
require_once($GLOBALS['BASE_PATH'] . '_config.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.users.php');

checkSession();

require_once($GLOBALS['LIBS_PATH'] . 'code.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.comm.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.direccion.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.crm.contacto.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.sys.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.folletos.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.javascript.php');

if(isset($boolReducido) && !$boolReducido) {
	require_once($GLOBALS['LIBS_PATH'] . 'class.proyectos.php');
	require_once($GLOBALS['LIBS_PATH'] . 'class.nota.php');
	require_once($GLOBALS['LIBS_PATH'] . 'class.crm.accion.php');
	require_once($GLOBALS['LIBS_PATH'] . 'class.asterisk.php');
}

require_once($GLOBALS['MODULE_PATH'] . '_incl/lan.es.php');

ob_start();

	$numRecordID = isset($_GET['id']) ? intval($_GET['id']) : -1;
	$operacion = isset($_GET['op']) ? $_GET['op'] : ($numRecordID == -1 ? 'add' : '');
	$numClienteID = isset($_GET['cliente']) ? $_GET['cliente'] : 0;

	$strNombre = $strCliente = $strDepartamento = $strCargo = $strNotas = $strResponsable = '';
	$numResponsable = $numEstado = 0;
	
	$objDatos = new contactoClass($numRecordID);
	switch($operacion) {
		case "add":
			$strCancelar = 'cancelContacto(' . $numClienteID . ')';
			break;
		case "edit":
		default:
			$strCancelar = 'cancelEdit()';
			if($objDatos->isConnected()) {
				$arrContacto = $objDatos->get(true);			
				if(is_array($arrContacto)){
					$numClienteID = $arrContacto['CLIENTE_ID'];
					$numResponsable = $arrContacto['RESPONSABLE'];
					$strCliente	= $arrContacto['CLIENTE'];
					$strNombre = $arrContacto['NOMBRE'];
					$strDepartamento = $arrContacto['DEPARTAMENTO'];
					$strCargo = $arrContacto['CARGO'];
					$strResponsable = isset($arrContacto['RESPONSABLE_NOMBRE']) ? $arrContacto['RESPONSABLE_NOMBRE'] : '';
					$numEstado = $arrContacto['ESTADO_ID'];
				}
			}
			break;
	}
	$strCliente = $strCliente == '' ? $objDatos->getNombreOwner($numClienteID) : $strCliente;
	//$objOpciones = new sysClass($numRecordID);	
	$objOpciones = new folletosClass($numRecordID);	
	
	// $objCalendario = new calendarioClass();
	//$objAccion = new accionClass();

?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<title>c l i e n t e s</title>
<link href="../_dom/layout.css" rel="stylesheet" type="text/css">
<link href="./_dom/layout.css" rel="stylesheet" type="text/css">
<link href="../_dom/mb/modalbox.css" rel="stylesheet" type="text/css">
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>               
<link href="../_dom/valums/fileuploader.css" rel="stylesheet" type="text/css">
<link href="../_dom/cal/calendar.css" rel="stylesheet" type="text/css">
<?php
	}
?>

<script type="text/javascript" src="../_dom/prototype/prototype.js"></script>
<script type="text/javascript" src="../_dom/prototype/scriptaculous.js?load=effects"></script>
<script type="text/javascript" src="../_dom/rsv.js"></script>
<script type="text/javascript" src="../_dom/mb/modalbox.js"></script>
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>
<script src="../_dom/valums/fileuploader.js" type="text/javascript"></script>
<script src="../_dom/cal/calendar.js" type="text/javascript"></script>
<?php
	}
?>

</head>
<body>
<?php
	require($GLOBALS['LIBS_PATH'] . 'inc.header.php');
?>
	<div id="main">
    	<div id="contenido">
  	    <div id="rsvErrors"></div>
			<div id="datos_edit" <?php echo $operacion != '' ? '' : 'style="display:none"'; ?>>
                <div>
                <h2><?php echo $TEXTOS['contacto_titulo']; ?></h2>
                <form id="formulario" class="dialogo">
                  <input id="op" type="hidden" value="<?php echo $operacion; ?>">
                  <input id="id" type="hidden" value="<?php echo $numRecordID; ?>">
                  <input id="cliente" type="hidden" value="<?php echo $numClienteID; ?>">
                    
                  <div class="field">
                    <label><?php echo $TEXTOS['contacto_cliente']; ?></label>
                                <span style="margin-bottom:10px"><?php echo $strCliente; ?></span>
                  </div>
                  
                  <div class="field">
                    <label for="nombre"><?php echo $TEXTOS['contacto_nombre']; ?></label>
                    <input id="nombre" size="60" maxlength="250" value="<?php echo $strNombre; ?>" />
                  </div>
                  <div class="field">
                    <label for="departamento"><?php echo $TEXTOS['contacto_dpto']; ?></label>
                    <input id="departamento" size="60" maxlength="250" value="<?php echo $strDepartamento; ?>" />
                  </div>
                  <div class="field">
                    <label for="cargo"><?php echo $TEXTOS['contacto_cargo']; ?></label>
                    <input id="cargo" size="60" maxlength="250" value="<?php echo $strCargo; ?>" />
                  </div>
                  
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>
                  <div class="field">
                        <label for="estado"><?php echo $TEXTOS['contacto_estado']; ?></label>
                        <select name="estado" id="estado">
                            <?php echo arrayAsoc2Select($gArrEstados, $numEstado); ?>
                        </select>
                  </div>
                  
                  <div class="field">
                    <label for="responsable"><?php echo $TEXTOS['contacto_responsable']; ?></label>
                    <select id="responsable">
                    <option value=""></option>
                        <?php echo sql2select($objDatos, str_replace(array('[[CLIENTE]]', '[[CONTACTO]]'), array($numClienteID, $numRecordID), QUERY_RESPONSABLE), $numResponsable); ?>            
                    </select>
                  </div>
<?php
	}
?>
                  <div class="formControls">
                    <input class="formButton" type="button" value="<?php echo $BOTON['cancelar']; ?>" id="cancel" onClick="<?php echo $strCancelar; ?>;return false;" />
                    <input class="formButton" type="button" value="<?php echo $BOTON['grabar']; ?>" id="grabar" onclick="saveContacto();return false;" />
        <?php
            if($operacion != 'add') {
        ?>
                        <a href="#" onclick="delContacto();return false;" style="margin-left:100px">[ <?php echo $BOTON['borrar']; ?> ]</a>
        <?php
            }
        ?>
                  </div>
                        
                </form>
                </div>
	    </div>
 
 <?php 
	if($operacion == '') {
 ?>
      <div id="datos_display">
				<div>
          <h2><a href="#" onclick="doEdit();"><span id="dato_nombre"><?php echo $strNombre; ?></span></a></h2>
          <div class="bloque">
            <span id="dato_cliente"><a href="cliente.php?id=<?php echo $numClienteID; ?>"><?php echo $strCliente; ?></a></span><br />
            <?php echo $strDepartamento != '' ? '<span><b>Departamento</b>: </span><span id="dato_departamento">' . $strDepartamento . '</span><br />': ''; ?>
            <?php echo $strCargo != '' ? '<span><b>Cargo</b>: </span><span id="dato_cargo">' . $strCargo . '</span><br />': ''; ?>
            <?php echo $numResponsable != 0 ? '<span><b>Reporta a</b> </span> <a href="../clientes/contacto.php?id=' . $numResponsable . '; ?>" class="button"> <span id="dato_cargo">' . $strResponsable . '</span></a><br />': ''; ?>
            <ul class="grupos" style="padding-top:12px" id="holdergrupos"></ul>
        </div>
        </div>    
    	</div>

			<div id="tabs">
	 			<ul>
					<li id="tabdirecciones"><?php echo $TABS['direcciones']; ?></li>
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>
                    <li id="tabproyectos"><?php echo $TABS['proyectos']; ?></li>
					<li id="tabcalendario"><?php echo $TABS['acciones']; ?></li>
					<li id="tabdocumentos"><?php echo $TABS['documentos']; ?></li>
					<li id="tabnotas"><?php echo $TABS['notas']; ?></li>
                    <li id="tabcomunicaciones"><?php echo $TABS['comunicaciones']; ?></li>
                    <li id="tabrelaciones"><?php echo $TABS['relaciones']; ?></li>
                    <li id="tabextranet"><?php echo $TABS['extranet']; ?></li>
<?php
	}
?>
				</ul>
			</div>
    
      <div id="paneles">

    	<div id="paneldirecciones">
<?php
				echo $objOpciones->renderActions('direcciones');
?>

        <div id="maindirecciones" style="clear:both;">
          <div id="holderdirecciones" style="margin-bottom:8px"></div>
          <ul id="comms" class="listadoble">
<?php
		if(isset($arrContacto['COMMS']) && is_array($arrContacto['COMMS'])) {
      foreach($arrContacto['COMMS'] as $arrRecord) {
?>
            <li id="commholder<?php echo $arrRecord['ID']; ?>">			
<?php
	      echo commsClass::render($arrRecord);
?>
            </li>
<?php
			}
		}
?>
          </ul>
          <ul id="dirs" class="listadoble">
<?php
    if(isset($arrContacto['DIRS']) && is_array($arrContacto['DIRS'])) {
      foreach($arrContacto['DIRS'] as $arrRecord) {
?>      
            <li id="dirholder<?php echo $arrRecord['ID']; ?>"style="z-index:1">			
<?php
      	echo direccionClass::render($arrRecord);
?>
            </li>
<?php
      }
		}
?>
          </ul>
	<div style="clear:both"></div>
<?php
		// las direcciones del cliente, no editables.
		$numComms = $objDatos->getCommsCliente();
		if($numComms) {
?>
		<ul id="comms2" class="listadoble">
<?php
			while($arrRecord = $objDatos->getNext()) {
?>
			<li>			
<?php
	      echo commsClass::render($arrRecord, false);
?>
            </li>
<?php		
			}
?>
		</ul>
<?php	
		}

		$numComms = $objDatos->getDireccionesCliente();
		if($numComms) {
?>
					<ul id="dirs2" class="listadoble">
<?php
			while($arrRecord = $objDatos->getNext()) {
?>
			 <li>			
<?php
	      echo direccionClass::render($arrRecord, false);
?>
            </li>
<?php		
			}
?>
					</ul>
<?php	
		}
?>
        </div>

	    </div>


<?php
	if(isset($boolReducido) && !$boolReducido) {
?>        
        <div id="panelproyectos" style="display:none">
<?php
				echo $objOpciones->renderActions('proyectos');
?>
        <div id="mainproyectos" style="clear:both;">        
<?php
		if($objDatos->getProyectos() == 0) {
			echo('Este contacto no ha pedido ningún proyecto.');
		} else {
?>
			<table border="0" cellspacing="2" cellpadding="4" id="resultados">
            	<thead>
                	<tr>
                    	<td style="width:60px">Estado</td>
                        <td>Ref.</td>
                        <td>Nombre</td>
                        <td>Inicio</td>
						<td>Fin</td>
            	     </tr>
                 </thead>
                 <tbody class="rayas">
<?php
   		while($arrProyecto = $objDatos->getNext()) {
   			$pro_id = $arrProyecto['ID'];
			$fondo2 = $arrProyecto['ESTADO'] == 7 ? 'verde' : '';
?>
									<tr class="<?php echo $fondo2; ?>">
										<td><span class="pstatus brdr6 <?php echo $gArrProyectoClases[$arrProyecto['ESTADO']]; ?>"><?php echo $gArrEstadoProyectos[$arrProyecto['ESTADO']]; ?></span></td>
										<td valign="top" class="data"  style="padding-left:12px"><a href="../proyectos/proyecto.php?id=<?php echo  $pro_id; ?>" class="button"><?php echo  $arrProyecto['REF_INTERNA']; ?></a></td>
										<td valign="top" class="data"><a href="../proyectos/proyecto.php?id=<?php echo  $pro_id; ?>" class="button"><?php echo  $arrProyecto['PROYECTO_NOMBRE']; ?></a></td>
										<td valign="top" class="data"><a href="../proyectos/proyecto.php?id=<?php echo  $pro_id; ?>" class="button"><?php echo  $arrProyecto['FECHA_INICIO']; ?></a></td>
										<td valign="top" class="data"><a href="../proyectos/proyecto.php?id=<?php echo  $pro_id; ?>" class="button"><?php echo  $arrProyecto['FECHA_FIN']; ?></a></td>
                  </tr>
<?php
		}	// while
?>
                    </tbody>
				</table>
<?php
		}
?>
		</div>
      </div>

    	<div id="panelcalendario" style="display:none"> 
<?php
				echo $objOpciones->renderActions('calendario');

		// $objCalendario->getEventos();	
		$arrAccionTipo = $objAccion->getArrayTipos();
		$arrAccion = $objAccion->getArrayAcciones();
		$numAcciones = $objDatos->getAcciones($numRecordID);
		
?>
		<div id="accion_edit" <?php echo 'style="display:none"'; ?>>
        
          <form> 
             <div class="field"><?php /* Google Calendar: TITLE PART1:*/?>
                <label for="accion_forma"><?php echo $TEXTOS['accion_forma']; ?></label>
                <select name="accion_forma" id="accion_forma">
                    <?php echo arrayAsoc2Select($arrAccionTipo, false); ?>
                </select>
             </div>
             
             <div class="field"><?php /* Google Calendar: TITLE PART2 */?>
                <label for="accion_motivo"><?php echo $TEXTOS['accion_motivo']; ?></label>
                <select name="accion_motivo" id="accion_motivo">
                    <?php echo arrayAsoc2Select($arrAccion, false); ?>       
                </select>
             </div>
             
             <div class="field"><?php /* Google Calendar: CONTENT */?>
                 <label for="accion_notas"><?php echo $TEXTOS['accion_notas']; ?></label>
                 <textarea name="accion_notas" id="accion_notas" rows="6" style="width:520px"></textarea>                
             </div>
             
             <div class="field">
                <label for="accion_futuro"><?php echo $TEXTOS['accion_futuro']; ?></label> 
                <input type="checkbox" id='accion_futuro' name="accion_futuro" value="1" onclick="doAccionEditFuturo();"/>     
             </div>
             
             <div id="accion_edit_futuro" <?php echo 'style="display:none"'; ?>>
                 <div class="field"><?php /* Google Calendar: STARTTIME */?>
                    <label for="accion_cuando"><?php echo $TEXTOS['accion_cuando']; ?></label> 
                    <input name="accion_cuando" id="accion_cuando" size="12" maxlength="12" /><img src="../_imgs/cal.png" id="cal1" />                  
                 </div>
             </div>
             
             <div class="formControls">
                        <input class="formButton" type="button" value="<?php echo $BOTON['cancelar']; ?>" id="cancel" onclick="cancelAccion();"/>
                        <input class="formButton" type="button" value="<?php echo $BOTON['grabar']; ?>" id="grabar" onclick="doAccion();"/>
           
             </div>  
          </form>
          
        </div>
<?php
		if($numAcciones == 0) {
			echo('<br/>&nbsp;&nbsp;No se han realizado acciones comerciales');
		} else {

?>   
        <table border="0" cellspacing="2" cellpadding="4" id="resultados">
            	<thead>
                	<tr>
                    	<td style="width:35px">Como</td>
                        <td style="width:100px">Que</td>
                        <td style="width:40px">Proyecto</td>
						<td style="width:180px">Notas</td>
                        <td style="width:50px">Para cuando</td>
                        <td style="width:50px">Creado</td>
                        <td style="width:70px; text-align:center">Completado</td>
            	     </tr>
                 </thead>
                 <tbody class="rayas">
<?php	
	
   		while($arrAcciones = $objDatos->getNext()) {
		$idAccion = $arrAcciones['ID'];
		$fondoEstado = $arrAcciones['DONE'] != 1 ? 'orange' : '';
?>
                   <tr class="<?php echo $fondoEstado; ?>">
                        <td valign="top" class="data" style="text-align:center"><?php echo  $arrAccionTipo[$arrAcciones['TIPO']]; ?></td>
                        <td valign="top" class="data" ><?php echo  $arrAccion[$arrAcciones['MOTIVO']]; ?></td>  
                        <td valign="top" class="data" style="text-align:center"><?php echo  $arrAcciones['PROYECTO'] == 0 ? 'NO' : $arrAcciones['PROYECTO']; ?></td>
                        <td valign="top" class="data"><?php echo  $arrAcciones['NOTAS']; ?></td>
                        <td valign="top" class="data"><?php echo  $arrAcciones['CUANDO']; ?></td>
                        <td valign="top" class="data"><?php echo  $arrAcciones['FECHA_CREACION']; ?></td>
                        <td valign="top" class="data" style="text-align:center"><input type="checkbox" name="accion_done" id="accion_done" value"1" onClick="doCompletedAccion(<?php echo  $idAccion; ?>);return false;" <?php if ($arrAcciones['DONE'] == 1) echo "checked"; else echo ""; ?> ></td>
                   </tr>
<?php
    		
		}	// while
?>
                    </tbody>
				</table>
<?php
		}
?>              
    	</div>
    	
        <div id="paneldocumentos" style="display:none">
<?php
				echo $objOpciones->renderActions('documentos');
				$strTabla = 'crm_documentos';
				$objUsers = new usersClass();
				$arrUsers = $objUsers->getUsers();
				$objDocus = new documentoClass($strTabla);
				$arrTiposArchivos = $objDocus->getTiposArchivosClientes();
				$arrFormatos = $objDocus->getFormatos();
?>
				<div id="maindocumentos" style="clear:both;">
             		<div id="file-uploader" style="display:none"></div>       
                </div>
     
<?php
		if(isset($arrContacto['DOCUMENTOS']) && is_array($arrContacto['DOCUMENTOS'])) {
?>			
			<table border="0" cellspacing="2" cellpadding="4" id="documentos">
                        <thead>
                        	<tr>
                            	<td>Archivo</td>
                                <td>Tipo</td>
                            	<td align="center">Formato</td>
                                <td align="center">Subido</td>
                                <td align="center">Por Usuario</td>
                                <td>Por Usuario</td>
            	            </tr>
                        </thead>
                        <tbody class="rayas">
<?php				
			foreach($arrContacto['DOCUMENTOS'] as $arrRecord) {
?>
					<tr>
					<td style width="350">
<?php
	    				echo '<a href="download.php?id=' . $arrRecord['ID'] . '">' . $arrRecord['DOCNAME'] . '</a> '; 
?>	
      				</td>
                    <td>
                    	<select name="lista_tipos" id="lista_tipos<?php echo $arrRecord['ID']; ?>" onChange="editTipoArchivo(<?php echo $arrRecord['ID']; ?>);" style="border:2px groove #006;">
								<?php echo arrayAsoc2Select($arrTiposArchivos, $arrRecord['TIPO'], true); ?>       
                        </select>
                    </td>
                    <td style width="100" align="center">
<?php
                    	 echo strtoupper($arrRecord['FORMATO']);
?>
                    </td>                    
                    <td style width="100" align="center">
<?php
                    	 echo $arrRecord['CREADO'];
?>
                    </td>                    
                   <td valign="top" style width="100" align="center">
						  <?php 
                              foreach($arrUsers as $arrSubUsers){
                                  if($arrSubUsers['ID'] == $arrRecord['CREADOR']){
                                      echo $arrSubUsers['NOMBRE'];
                                  }
                              }; 
                          ?>
                    </td>
                    <td width="200">
<?php						 
				//Find the source path of the file to open with google:
				if($objDocus->isConnected()) {
					$arrDocu = $objDocus->get($arrRecord['ID']);
					if(is_array($arrDocu)) {
						$strSrcFile = $arrDocu['PATH'] . '/' . $arrDocu['FILENAME'];
						$strFileName = $arrDocu['DOCNAME'] . '.' . $arrDocu['FORMATO'];
					}
				}
				if(in_array($arrRecord['FORMATO'], $arrFormatos) && filesize($strSrcFile) < 2000000) {
					echo '<a href="http://docs.google.com/viewer?url=https://alger.deltatext.com/clientes/download.php?id=' . $arrRecord['ID'] . '" target="_blank" >Ver online</a>';
				}
?>	
              		 </td>
                 </tr>
<?php
			$arrIdDocus[] = $arrRecord['ID'];
			
			}
		}
?>
	      		</tbody>
			</table>       
      </div>
            
    	<div id="panelnotas" style="display:none">
<?php
				echo $objOpciones->renderActions('notas');
?>
        <div id="mainnotas" style="clear:both;">
          <div id="holdernotas" style="margin-bottom:8px"></div> 
          
					<ul id="notas">
<?php
	    if(isset($arrContacto['NOTAS']) && is_array($arrContacto['NOTAS'])) {
	      foreach($arrContacto['NOTAS'] as $arrRecord) {
?>
					<li id="notaholder<?php echo $arrRecord['ID']; ?>">
<?php
		      echo notaClass::render($arrRecord);
?>	
      			</li>
<?php
				}
			}
?>
					</ul>   
  			</div>
      </div>
      
      <div id="panelextranet" style="display:none">
<?php
				echo $objOpciones->renderActions('extranet');
?>
        <div id="mainextranet" style="clear:both;">
        
<?php
				$objUsuarios = new usersClass();
				$arrLoginDetails = $objUsuarios->getContactoLogin($numRecordID);
				if(is_array($arrLoginDetails)) {
					$username = $arrLoginDetails['username'];
?>				
                     <div style="padding-top: 20px;"><b> Nombre de usuario: </b><?php echo  $arrLoginDetails['username']; ?></div><br/>
                     <div><b> Email: </b><?php echo  $arrLoginDetails['email']; ?></div> 
<?php
				} else {
					$username = '';	
				}
?> 
                <div id="client_access" <?php echo 'style="display:none"'; ?>>
                    <form method="post" action="users_db.php" name="formulario" id="formulario">
                    <fieldset id="users">
                    <input id="nombre_contacto" type="hidden" value="<?php echo $strNombre; ?>">
                    <input id="id_cliente" type="hidden" value="<?php echo $numClienteID; ?>">
            
                        <div class="field">
                            <label for="username"><?php echo $TEXTOS['client_username']; ?></label>
                            <input name="username" id="username" value="<?php echo $username; ?>" />
                        </div>
                        <div class="field">
                            <label for="email"><?php echo $TEXTOS['client_email']; ?></label>
                             <select name="email" id="email">
                                        <?php echo sql2Select($objDatos, 'SELECT com_direccion AS ID, com_direccion AS LABEL FROM crm_comunicaciones, crm_cliente_contactos WHERE com_tipo = 4 AND com_contacto = ' . $numRecordID . ' AND com_owner = cont_id ', 0); ?>
                             </select>
                        </div>
            
                        <div class="field">
                            <label for="password"><?php echo $TEXTOS['client_password']; ?></label>
                            <input name="password" id="password" /> &nbsp Introduce un pwd para cambiarlo.
                        </div>
            
                        <div class="formControls">
                            <input class="formButton" type="button" name="cancel" value="Cancelar" id="cancel" onclick="cancelClientAccess()" />
                            <input class="formButton" type="button" name="Submit" value="<?php echo $BOTON['client_save']; ?>" id="Submit" onclick="doClientAccessAdd()" />
<?php
                        if($operacion != 'add') {
?>
                        <!--<a href="#" onclick="" style="margin-left:100px">[ borrar ]</a>-->
<?php
                        }
?>
                        </div>     
                    </fieldset>
                    </form> 
              </div> 
		</div>
        
      	</div>
        
        <div id="panelrelaciones" style="display:none">
<?php
				echo $objOpciones->renderActions('relaciones');
?>

		<div id="minion_edit" <?php echo 'style="display:none"'; ?>>
        <form>          
         <div class="field">             
             <label for="minion_nombre"><?php echo $TEXTOS['minion_nombre']; ?></label>
             <select id="minion_nombre">
                    <option value=""></option>
                        <?php echo sql2select($objDatos, str_replace(array('[[CLIENTE]]', '[[CONTACTO]]'), array($numClienteID, $numRecordID), QUERY_RESPONSABLE), $numResponsable); ?>            
                    </select>   
         </div>
         
         <div class="formControls">
                    <input class="formButton" type="button" value="<?php echo $BOTON['cancelar']; ?>" id="cancel" onclick="cancelMinionAdd();"/>
                    <input class="formButton" type="button" value="<?php echo $BOTON['grabar']; ?>" id="grabar" onclick="doMinion();"/>
       
         </div>
                   
        </form>
        </div>
        
          <div id="mainrelaciones" style="clear:both;">
          
              <div id="holderrelaciones" style="margin-bottom:8px"></div> 
              
   <?php
		if($objDatos->getMinions() == 0) {
			echo('<br/>&nbsp;&nbsp;No tiene empleados a cargo');
		} else {
?>
			<table border="0" cellspacing="2" cellpadding="4" id="resultados">
            	<thead>
                	<tr>
                    	<td>Empleados a cargo</td>
                        <td></td>
            	     </tr>
                 </thead>
                 
                 <tbody class="rayas">
<?php
   		while($arrMinions = $objDatos->getNext()) {
?>
                   <tr>
                        <td valign="top" class="data"><a href="../clientes/contacto.php?id=<?php echo  $arrMinions['ID']; ?>" class="button"><?php echo  $arrMinions['NOMBRE']; ?></a></td>
                        <td valign="top" class="data" onClick="deleteMinion(<?php echo  $arrMinions['ID']; ?>);"><?php echo  'Borrar'; ?></td>
                   </tr>
<?php
    		
		}	// while
?>
                    </tbody>
				</table>
<?php
		}
?>
          </div>      
   		</div>
<?php
		}
?>
        
    </div>
    
<?php
	}
?>
  </div>
  <div id="columna">
<?php
	require_once($GLOBALS['LIBS_PATH'] . 'inc.acciones.php');
?> 		
  </div>
</div>
<?php
	require($GLOBALS['LIBS_PATH'] . 'inc.footer.php');
?>
</body>
<?php
	$objJS = new jsLoaderClass();

	$objJS->order();

	$objJS->numClienteID = $numClienteID;
	$objJS->numNotaOwner = $objJS->numContactoID = $numRecordID;
	$objJS->arrComms = getListaJavaScript(LISTA_COMMS);
	$objJS->arrDirs = getListaJavaScript(LISTA_DIRECCIONES);	
	
	$objJS->textoAyuda = $objJS->text($TEXTOS['ayuda']);
	$objJS->textoConfirmEdit = $objJS->text($TEXTOS['confirmar_edicion']);
	$objJS->textoConfirmDelete = $objJS->text($TEXTOS['confirmar_borrado']);

	$objJS->reglaNombre = '"required,nombre,' . $ERROR['rsv_nombre'] . '"';

	$objJS->addFile($GLOBALS['BASE_PATH'] . '_dom/code.js');
	$objJS->addFile($GLOBALS['BASE_PATH'] . '_dom/box.js');
	$objJS->addFile($GLOBALS['BASE_PATH'] . '_dom/tabs.js');
	$objJS->addFile($GLOBALS['BASE_PATH'] . '_dom/code.comms.js');
	$objJS->addFile($GLOBALS['MODULE_PATH'] . '_dom/code.js');
	
	$objJS->setOutput($GLOBALS['MODULE_PATH'] . '_dom/_cliente.js');

	$objJS->save();
?>
<script type="text/javascript" src="./_dom/_cliente.js"></script>
 <?php 
	if($operacion == '') {
 ?>

<script>
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>
	Calendar.setup({inputField:"accion_cuando", ifFormat:"%d/%m/%Y", button:"cal1", align:"Bl", singleClick:true});
	Tabs.init(['direcciones', 'proyectos', 'calendario', 'documentos', 'notas', 'comunicaciones', 'extranet', 'relaciones']);
<?php
	} else {
?>
		Tabs.init(['direcciones']);
<?php
	}
?>
	rsv.errorTextIntro = "<?php echo $ERROR['rsv_error']; ?>";
	
</script>
<?php
	}
?>
</html>