<?php 
/////////////////////////////////////////////////////////////////////////////////////////
//
//	this file has been generated by sformi, the clever tool for lazy developers.
//
//	template v6 - 16062010
//		v6 changed structure of includes
//
//	160710 - v1
//

ini_set ('error_reporting', E_ALL);
ini_set ('display_errors', '1');

session_start();

require_once('./_config.php');
require_once($GLOBALS['BASE_PATH'] . '_config.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.users.php');

checkSession();

require_once($GLOBALS['LIBS_PATH'] . 'code.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.crm.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.sys.php');

require_once($GLOBALS['MODULE_PATH'] . '_incl/lan.es.php');

	$objDatos = new crmClass();
	if(!$objDatos->isConnected()) {
	// ha ocurrido un error con la base de datos. informamos y ande vamos?
		die('<p>An error has occurred while accessing the database: ' . mysql_error());
	}
	
	// tipo por defecto: 1 = sectores
	$numTipo = (isset($_GET['tipo']) ? $_GET['tipo'] : 1);
	
	$gStartRec = (isset($_GET['start']) ? $_GET['start'] : 0);
	$gLimit = 25;
	$numTotal = 0;
	$strBusqueda = $strCampoBusqueda = $strTipoBusqueda = '';
 	$boolBuscando = false;

	// vengo nuevo o vengo de buscar?
	if(isset($_SESSION['_BUSQUEDA']) && $_SESSION['_BUSQUEDA']['redir'] == './clientes/grupos.php') {
		$arrBusqueda = $_SESSION['_BUSQUEDA'];
		$boolBuscando = true;
		 // relleno los campos que mostraré al usuario
		$strBusqueda = $strCampoBusqueda = $arrBusqueda['buscar'];
		$strTipoBusqueda = 'form';
	}
	
	$numRecords = $objDatos->searchGrupos($numTipo);
  // Iván: 19/08/2012 - Ya se está haciendo en a comprobación del checkSession()
  // 		$objOpciones = new sysClass();
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>c l i e n t e s</title>
	<link href="../_dom/layout.css" rel="stylesheet" type="text/css">
	<link href="./_dom/layout.css" rel="stylesheet" type="text/css">
  <link href="../_dom/mb/modalbox.css" rel="stylesheet" type="text/css">
	<script src="../_dom/prototype/prototype.js" type="text/javascript"></script>
	<script type="text/javascript" src="../_dom/prototype/scriptaculous.js?load=effects"></script>
	<script src="../_dom/mb/modalbox.js" type="text/javascript"></script>
	<script src="../_dom/code.js" type="text/javascript"></script>
	<script src="./_dom/code.js" type="text/javascript"></script>
<style>
.listadoble li{height:35px}
</style>
</head>
<body>
<?php
	require($GLOBALS['LIBS_PATH'] . 'inc.header.php');
?>
		<div id="main">
    		<div id="contenido">
<?php
	if(1==0) {
?>
				<div id="buscador">
          <form action="../redir.php" method="post">
            <input type="hidden" name="redir" value="./clientes/grupos.php" />
            <fieldset>
              <div class="field">
                <label for="buscar">Buscar:</label>
                <input id="buscar" name="buscar" size="50" title="Escribe el nombre del cliente o el nombre del contacto que quieras encontrar" value="<?php echo $strCampoBusqueda; ?>"/><select name="tipo" id="tipo">
                    <option value="0">Todos</option>
	                  <?php echo arrayAsoc2Select($gArrGrupos, $numTipo); ?>
                  </select>
              </div>
              <div class="formControls">
                <input type="submit" value="Buscar" class="formButton" name="submit_search">
              </div>
            </fieldset>
          </form>
        </div>
<?php
	}
?>	
				<ul class="grupos" style="padding-left:12px;margin:12px">
<?php
			foreach($gArrGrupos as $numId => $strGrupo) {
?>
					<li><a href="grupos.php?tipo=<?php echo $numId; ?>"><?php echo $strGrupo; ?></a></li>
<?php
			}	
?>
				</ul>
<?php
	if(!$numRecords) {
		if($boolBuscando) {
?>
				<div></div>        
<?php
		}
	} else {

		if($numTotal > $gLimit) {
			if($numGrupoID) {
				$strParams = 'grupo=' . $numGrupoID;
			} else {
				$strParams = '';
			}
?>
				<div id="paginator_top" style="padding-left:12px;margin-left:12px">
					<span class="paginator">
						<?php echo drawPaginator($numTotal, $gStartRec, $gLimit, 'pag_button', $strParams); ?>
					</span>
				</div>
<?php
		}
?>

				<div id="maingrupos" class="bloque" style="clear:both">
					<ul class="listadoble" style="border:0">
<?php
		while($arrRecord = $objDatos->getNext()) {
?>
							<li>
      					<h3><a href="index.php?grupo=<?php echo $arrRecord['ID']; ?>"><?php echo $arrRecord['LABEL']; ?></a></h3>
								<p style="font-size:10px">(<?php echo $arrRecord['CUANTOS'];?> cliente<?php echo $arrRecord['CUANTOS'] > 1 ? 's' : ''; ?>)
                <p><?php echo $arrRecord['DESCR'];?>
  	    			</li>
<?php
		}
?>
					</ul>
  			</div>
	
<?php
	}
?>
			</div>
      
      <div id="columna">
<?php
	require_once($GLOBALS['LIBS_PATH'] . 'inc.acciones.php');
	
	require_once('./_incl/inc.grupos.php');
?>
			</div>
		</div>
</body>
</html>