<?php 
/////////////////////////////////////////////////////////////////////////////////////////
//
//	this file has been generated by sformi, the clever tool for lazy developers.
//
//	template v6 - 16062010
//		v6 changed structure of includes
//
//	160710 - v1
//

ini_set ('error_reporting', E_ALL);
ini_set ('display_errors', '1');

session_start();

ob_start();
require_once('./_config.php');
require_once($GLOBALS['BASE_PATH'] . '_config.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.users.php');

checkSession();

require_once($GLOBALS['LIBS_PATH'] . 'code.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.crm.php');
require_once($GLOBALS['LIBS_PATH'] . 'class.sys.php');
require_once($GLOBALS['LIBS_PATH'] . 'lan.es.php');

require_once($GLOBALS['MODULE_PATH'] . '_incl/lan.es.php');

	$objDatos = new crmClass();
	if(!$objDatos->isConnected()) {
	// ha ocurrido un error con la base de datos. informamos y ande vamos?
		die('<p>An error has occurred while accessing the database: ' . mysql_error());
	}
	
	if(isset($_GET['t'])) {
		unset($_SESSION['_BUSQUEDA']);
	}

	$strTipoListado = 'e';
	
	//$strTipoListado = isset($boolReducido) && $boolReducido ? 'e' : (isset($_GET['t']) ? $_GET['t'] : (isset($_GET['grupo']) ? 'e' : 'c'));
	
	// this code is for the "paginator"
	$gStartRec = isset($_GET['start']) ? $_GET['start'] : 0;
	$gLimit = isset($_GET['limit']) ? $_GET['limit'] : 25;
	$numTotal = 0;
	$strBusqueda = $strCampoBusqueda = $strTipoBusqueda = '';
	$numEstado = $numSector = $numValoracion = 0;
 	$boolBuscando = false;
	$numRecords = 0;

	// vengo nuevo o vengo de buscar?
	//$arrBusqueda = $strTipoListado == 'e' ? array('estado' => 1) : NULL;
	$arrBusqueda = NULL;
	
	$strTipoBusqueda = 'form';
	$numGrupoID = isset($_GET['grupo']) ? intval($_GET['grupo']) : 0;
	if($numGrupoID) {
		$strTipoBusqueda = 'grupo';
		$arrBusqueda = array('grupo' => $numGrupoID);
		$boolBuscando = true;
	} else {
		if(isset($_SESSION['_BUSQUEDA']) && $_SESSION['_BUSQUEDA']['redir'] == './clientes/index.php') {
			$arrBusqueda = $_SESSION['_BUSQUEDA'];	
			$boolBuscando = true;
			 // relleno los campos que mostraré al usuario
			$strBusqueda = $strCampoBusqueda = $arrBusqueda['buscar'];
			$numEstado = $arrBusqueda['estado'];
			$strTipoListado = $arrBusqueda['tipo'];
		}
	}

  // Ivan - 04/07/2012	
	$strOrden = isset($_GET['s']) ? $_GET['s'] : '';

	
	// añadir aquí la lógica para que determinados usuarios puedan ver el listado.
	if($strTipoListado == 'e') {
//		if($boolBuscando) {
			$numRecords = $objDatos->searchClientes($numTotal,
																							array('search' => $strTipoBusqueda,
																										'value' => $arrBusqueda,
																										'start' => $gStartRec,
																										'limit' => $gLimit,
																										'order' => $strOrden)); // Ivan - 04/07/2012
//		}
		$strTip = 'Escribe el nombre del cliente o el nombre del contacto que quieras encontrar';
	} else {
//		if($boolBuscando) {
			$numRecords = $objDatos->searchContactos($numTotal, array('search' => 'form', 'value' => $arrBusqueda, 'start' => $gStartRec, 'limit' => $gLimit));		
//		}
		$strTip = 'Escribe el nombre del contacto que quieras encontrar';
	}
	if($boolBuscando && $numRecords == 1) {
		$arrRecord = $objDatos->getNext();
		if(is_array($arrRecord)){
			unset($_SESSION['_BUSQUEDA']);
			if($strTipoListado == 'e') {
				header('Location:cliente.php?id=' . $arrRecord['ID']);
			} else {
				header('Location:contacto.php?id=' . $arrRecord['ID']);	
			}
		} else {
			// otro error? menudo día llevamos	
		}
	}
  // Iván: 19/08/2012 - Ya se está haciendo en a comprobación del checkSession()
  // 		$objOpciones = new sysClass();
?>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>c l i e n t e s</title>
	<link href="../_dom/layout.css" rel="stylesheet" type="text/css">
	<link href="./_dom/layout.css" rel="stylesheet" type="text/css">
  <link href="../_dom/mb/modalbox.css" rel="stylesheet" type="text/css">
	<script src="../_dom/code.js" type="text/javascript"></script>
	<script src="../_dom/prototype/prototype.js" type="text/javascript"></script>
	<script type="text/javascript" src="../_dom/prototype/scriptaculous.js?load=effects"></script>
	<script src="../_dom/mb/modalbox.js" type="text/javascript"></script>
	<script src="./_dom/code.js" type="text/javascript"></script>
	
</head>
<body>
<?php
	require($GLOBALS['LIBS_PATH'] . 'inc.header.php');
?>
		<div id="main">
    		<div id="contenido">
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>               
                <ul class="hangcontroles">
            		<li><a href="index.php?t=e" <?php echo $strTipoListado == 'e' ? 'class="activa"' : ''; ?>>Empresas</a></li>
                	<li><a href="index.php?t=c" <?php echo $strTipoListado == 'c' ? 'class="activa"' : ''; ?>>Contactos</a></li>
            	</ul>
<?php
	}
?>
                <div id="buscador">
                    <form action="../redir.php" method="post">
                        <input type="hidden" name="redir" value="./clientes/index.php" />
                        <input type="hidden" name="tipo" value="<?php echo $strTipoListado; ?>" />
                        <div class="field">
	                        <label for="buscar">Nombre</label>
                            <input id="buscar" name="buscar" size="50" title="<?php echo $strTip; ?>" value="<?php echo $strCampoBusqueda; ?>"/>
<?php
	if(isset($boolReducido) && !$boolReducido) {
?>               
                            <select name="estado" id="estado">
	                            <option value="0">Todos</option>
    	                       <?php echo $strTipoListado == 'e' ? arrayAsoc2Select($gArrEstados, $numEstado) : sql2Select($objDatos, QUERY_GRUPOS_CONTACTOS, $numEstado); ?>
                            </select>
<?php
	}
?>
                            <input type="submit" value="Buscar" class="formButton" name="submit_search" style="margin:-1px 0 0 12px">
                        </div>
                    </form>
                </div>
<?php
	if(!$numRecords) {
		if($boolBuscando) {
?>
				<div class="error"><?php echo $TEXTOS['no_resultados']; ?></div>        
<?php
		}
	} else {
?>
				<div id="resultados">
					<div id="paginator_top">
          				<span style="font-size:11px">
							<?php echo $numRecords . ($strTipoListado == 'e' ? ' clientes' : ' contactos') . ($numRecords != $numTotal ? ' de ' . $numTotal : '') . ($strTipoBusqueda == 'grupo' ? ' en el grupo <b>' . $objDatos->getLabelGrupo($numGrupoID) . '</b>.' : '.'); ?>
            			</span>
<?php
		if($numTotal > $gLimit) {
			$strParams = $numGrupoID ? 'grupo=' . $numGrupoID : '';		
?>
						<span class="paginator">
							<?php echo drawPaginator($numTotal, $gStartRec, $gLimit, 'pag_button', $strParams); ?>
						</span>
<?php
		}
?>
					</div>

<?php
		if($strTipoListado == 'e') {
?>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <th width="350" style="padding-left:12px"><a href="./index.php?s=nom">Nombre</a></th>
                <th width="260"><a href="./index.php?s=sec">Sector</a></th>
                <th width="80"><a href="./index.php?s=est">Estado</a></th>
            </tr>
        </thead>
        <tbody class="rayas">
<?php
	while($arrRecord = $objDatos->getNext()) {
		$cli_id = $arrRecord['ID'];
?>
            <tr>     
                <td width="350" valign="top" style="padding-left:12px"><a href="cliente.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['NOMBRE']; ?></a></td>
                <td width="260" valign="top"><a href="cliente.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['SECTOR']; ?>&nbsp;</a></td>
                <td width="80" valign="top"><a href="cliente.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $objDatos->getLabelEstado($arrRecord['ESTADO']); ?></a></td>
            </tr>
<?php
		
	}	// while
?>
        </tbody>
    </table>
<?php
		} else {
?>

    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <thead>
            <tr>
                <td width="200" style="padding-left:12px">Nombre</td>
                <td width="200">Cliente</td>
                <td width="150">email</td>
                <td width="90">Teléfono</td>
            </tr>
        </thead>
        <tbody class="rayas">
<?php
	while($arrRecord = $objDatos->getNext()) {
		$cli_id = $arrRecord['ID'];
?>
            <tr>     
                <td width="200" valign="top" style="padding-left:12px"><a href="contacto.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['NOMBRE']; ?></a></td>
                <td width="200" valign="top"><a href="contacto.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['CLIENTE']; ?>&nbsp;</a></td>
                <td width="150" valign="top"><a href="contacto.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['EMAIL']; ?></a></td>
                <td width="90" valign="top" align="right"><a href="contacto.php?id=<?php echo $cli_id; ?>" class="button"><?php echo $arrRecord['MOVIL']; ?></a></td>
            </tr>
<?php
		
	}	// while
?>
        </tbody>
    </table>


<?php		
		}
?>
				</div>
<?php
	}
?>
			</div>
      
      <div id="columna">
<?php
	require_once($GLOBALS['LIBS_PATH'] . 'inc.acciones.php');
	
	if(isset($boolReducido) && !$boolReducido) {
		require_once('./_incl/inc.grupos.php');
	}
?>
			</div>
		</div>
        
<?php
	require($GLOBALS['LIBS_PATH'] . 'inc.footer.php');
?>
</body>
</html>