<?php 
/////////////////////////////////////////////////////////////////////////////////////////
//
//	this file has been generated by sformi, the clever tool for lazy developers.
//
//	template v5 - 08082007
//
//	160710 - v1
//

ini_set ('error_reporting', E_ALL);
ini_set ('display_errors', '1');

session_start();

require_once('../../_config.php');
require_once('../../_incl/class.crm.php');
require_once('../../_incl/code.php');

	$id = isset($_GET['id']) ? intval($_GET['id']) : -1;
	$operacion = isset($_GET['op']) ? $_GET['op'] : ($id == -1 ? 'add' : 'edit');
	$strNombre = $strDescripcion = '';
	
	$objDatos = new grupoClass($id);
	switch($operacion) {
		case "edit":
			if($objDatos->isConnected()) {
				$arrRecord = $objDatos->get();
				if (is_array($arrRecord)) {
					$strNombre = $arrRecord['NOMBRE'];
					$strDescripcion = $arrRecord['DESC'];
				}
			}
			break;
		case "add":
		default:
			break;
	}
	ob_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Editar un grupo</title>
</head>
<body>
<form id="grupo" class="dialogo">
	<input id="op_dlog" type="hidden" value="<?php echo $operacion; ?>">
	<input id="id_dlog" type="hidden" value="<?php echo $id; ?>">

	<div class="field">
		<label for="nombre_dlog">Nombre</label><input id="nombre_dlog" type="text" size="32" maxlength="100" value="<?php echo $strNombre; ?>" />
	</div>
    <div class="field">
    	<label for="tipo_dlog">Tipo</label><select id="tipo_dlog">
        <?php echo arrayAsoc2Select($gArrGrupos);?>
        </select>
    </div>
	<div class="field">
		<label for="descripcion_dlog">Descripción</label><textarea id="descripcion_dlog" cols="30" rows="2"><?php echo $strDescripcion; ?></textarea>
	</div>

	<div class="formControls">
		<input class="formButton" type="button" value="Cancelar" id="cancel_dlog" onClick="Modalbox.hide();return false;" />
        <input class="formButton" type="button" value="Grabar" id="grabar_dlog" onclick="saveGrupo();return false;" />
	</div>
</form>
</body>
</html>