<?php 
/////////////////////////////////////////////////////////////////////////////////////////
//
//	this file has been generated by sformi, the clever tool for lazy developers.
//
//	template v5 - 08082007
//
//	160710 - v1
//

ini_set ('error_reporting', E_ALL);
ini_set ('display_errors', '1');

session_start();

require_once('../../_config.php');
require_once('../../_incl/class.crm.php');
require_once('../../_incl/code.php');
require_once('../../_incl/lan.es.php');

$strTipoGrupo = isset($_GET['t']) ? 'contacto' : 'cliente';

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Editar un grupo</title>
</head>
<body>
<form id="grupo" class="dialogo">
	<input id="op_dlog" type="hidden" value="<?php echo $strTipoGrupo; ?>">

<?php
	if($strTipoGrupo == 'cliente') {
?>
  <div class="field">
  	<span><strong>Tipo:</strong></span> <select id="tipo_dlog" onchange="getGrupos('<?php echo $strTipoGrupo; ?>');" style="background-color:white">
    <?php echo arrayAsoc2Select($gArrGrupos);?>
    </select>
  </div>
<?php
	}
?>
  <div style="height:242px;clear:both;overflow:auto;margin-bottom:8px;font-size:13px;border:1px solid #999;background-color:white">
		<table border="0" cellspacing="0" cellpadding="0" width="100%" id="dlog_tabla"></table>
	</div>
	 <div style="text-align:right">
	  <input class="formButton" type="button" value="<?php echo $BOTON['addgrupo']; ?>" onclick="addGrupo('<?php echo $strTipoGrupo; ?>');return false;" />
	  <input class="formButton" type="button" value="<?php echo $BOTON['cancelar']; ?>" id="grabar" onclick="Modalbox.hide();return false;" style="margin-right:0" />
   </div>
</form>
<script>
	getGrupos('<?php echo $strTipoGrupo; ?>');
</script>
</body>
</html>